# Generated by Django 5.1.7 on 2025-03-21 13:11

import todo.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, validators=[todo.models.validators.HexCodeValidator()]),
        ),
    ]
