# Generated by Django 5.1.7 on 2025-03-23 14:24

import todo.models.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, unique=True, validators=[todo.models.validators.HexCodeValidator()]),
        ),
    ]
