# Generated by Django 5.1.7 on 2025-03-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_color_hex_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'get_latest_by': 'created_date', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'created_date', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'get_latest_by': 'created_date', 'ordering': ['priority']},
        ),
        migrations.AlterModelTable(
            name='color',
            table='color',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='todoitem',
            table='todo_item',
        ),
    ]
