# Generated by Django 5.1.7 on 2025-03-29 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_color_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.color')),
            ],
            options={
                'db_table': 'todo_list',
                'ordering': ['name'],
                'get_latest_by': 'created_date',
            },
        ),
    ]
