# Generated by Django 5.1.7 on 2025-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='todo_items',
            field=models.ManyToManyField(to='todo.todoitem'),
        ),
    ]
