# Generated by Django 5.1.7 on 2025-03-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todolist_todo_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='todo_items',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='color',
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
