# Generated by Django 5.1.7 on 2025-03-29 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_remove_todolist_todo_items_remove_todolist_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.color')),
            ],
            options={
                'db_table': 'todo_list',
                'ordering': ['name'],
                'get_latest_by': 'created_date',
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('title', models.CharField(max_length=64, unique_for_date='created_date')),
                ('description', models.CharField(max_length=256)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('synced', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todolist')),
            ],
            options={
                'db_table': 'todo_item',
                'ordering': ['priority'],
                'get_latest_by': 'created_date',
            },
        ),
    ]
