# Generated by Django 5.1.7 on 2025-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todolist_todoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='todo.tag'),
        ),
    ]
