# Generated by Django 5.1.7 on 2025-04-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_todoitem_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='tags',
        ),
    ]
