# Generated by Django 5.1.7 on 2025-04-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_todoitem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.tag')),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todoitem')),
            ],
            options={
                'ordering': ['todo_item'],
                'get_latest_by': 'created_date',
            },
        ),
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, through='todo.TodoItemTag', to='todo.tag'),
        ),
    ]
