# Generated by Django 5.1.7 on 2025-04-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todoitemtag_todoitem_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todoitemtag',
            table='todo_item_tag',
        ),
    ]
