# Generated by Django 5.1.7 on 2025-04-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_todoitemtag_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.todolist'),
        ),
    ]
