# Generated by Django 5.1.7 on 2025-04-07 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_todoitem_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'get_latest_by': 'created_date', 'ordering': ['list', 'priority']},
        ),
    ]
