# Generated by Django 5.2.11 on 2026-03-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_todoitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, through='todo.TodoItemTag', through_fields=('todo_item', 'tag'), to='todo.tag'),
        ),
    ]
