# Generated by Django 5.2.11 on 2026-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_todolist_description_alter_todoitem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
