# Generated by Django 5.2.11 on 2026-03-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Event duration in minutes for calendar export. Defaults to 30 if not set.', null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='importance',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'High'), (5, 'Medium'), (9, 'Low')], default=0),
        ),
    ]
