# Generated by Django 6.0.4 on 2026-04-30 22:44

import django.db.models.deletion
import todo.models.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_add_importance_and_duration_to_todoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_lists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=7, validators=[todo.models.validators.HexCodeValidator()]),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_color_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('owner', 'hex_code'), name='unique_color_hex_per_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='todolist',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_list_name_per_user'),
        ),
    ]
